### ISSUE TITLE
Student ID login issue

### ISSUE THREAD

**Issue by BlissMediaSolutions** [BlissMediaSolutions/Book-Xchange#5]
The Login page appears it may still be trying to use the email address instead of the StudentID;

When trying to login (with a correct) ID & password, it gets rejected... possibly due to the ID/email issue
![student login](https://cloud.githubusercontent.com/assets/10906791/15446503/6ee2b126-1f66-11e6-92c1-7434c4da3395.jpg)

Within the MySQL when this was run, there was 1 student registered & their details i was trying to use.
![student dbase](https://cloud.githubusercontent.com/assets/10906791/15446507/9029be7e-1f66-11e6-83b2-c114ab281fc3.jpg)

**Comment by s9998373** [comment]
I had this problem last night.

The issue was that the database was not connecting due to 127.0.0.1 not working, had to change to local host.

An error is not shown because PHP is corrupting the JSON response by prefixing it with "could not connect to database". I'd advise to move the error into the JSON response, so that it can be presented nicely to the user.

Assuming this is the same issue.

**Comment by BlissMediaSolutions** [comment]
No actual issue - forgot to change the config for settings.php when testing.
But at the same time, it would be good to have it return an error saying "could not connect to database", given this was the issue.
